### ISSUE TITLE
How to Use print/message?

### ISSUE THREAD

**Issue by christopherwoo** [Skycoder42/QCliParser#1]
How to Use arguments like print/message:
> ./demo print colored/size/season/  

won't work.

**Comment by Skycoder42** [comment]
The print command is a command group (aka. a `QCliContextNode`), that contains further commands. If you run
```
./demo print --help
```
You will see that you can use the following further commands: `tree` and `sum`
These two are both `QCliLeafNode`s, which means they are not followed by any additional commands, but only positional arguments. If you run for example
```
./demo print tree --help
```
You will see that you can now specify `--color`, `--season` and `--size` as options. If you where to use all three of those, you would call
```
./demo print tree --colored --season spring --size 100
```
The command will work.

**Comment by christopherwoo** [comment]
OK, thanks.
